### ISSUE TITLE
HTML in the message should be escaped

### ISSUE THREAD

**Issue by benface** [craftcms/contact-form#104]
Any HTML entered by the user in the message field is rendered raw in the email's body. I believe that's a security issue, and if not, it's just annoying. :P

**Comment by brandonkelly** [comment]
Agree that should not be the case.

**Comment by brandonkelly** [comment]
@benface What version of Craft & Contact Form are you using?

**Comment by benface** [comment]
@brandonkelly Version 1.9.1 running on Craft CMS 2.6.2993.

**Comment by takobell** [comment]
Fixed in https://github.com/craftcms/contact-form/releases/tag/1.9.2

**Comment by benface** [comment]
@angrybrad Still seeing this in version 2.1.1 running on Craft CMS 3.0.0-RC10.1.

**Comment by benface** [comment]
@angrybrad Did you see this? Should I submit a new issue?

**Comment by angrybrad** [comment]
@MakeilaLundy @Radabaugh this needs to be addressed for the v2 branch as well.
